name: money_tracker
description: Money tracker app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  provider: ^6.1.2
  intl: ^0.20.0
  fl_chart: ^1.0.0
  excel: ^4.0.3
  share_plus: ^11.0.0
flutter:
  uses-material-design: true
